apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: backend
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: career-advisor/conversations-service
      context: .
      docker:
        dockerfile: microservices/services/conversations-service/Dockerfile
      sync:
        manual:
          - src: "microservices/services/conversations-service/src/**/*.py"
            dest: "/app/microservices/services/conversations-service/src"
          - src: "microservices/shared/**/*.py"
            dest: "/app/microservices/shared"
    - image: career-advisor/llm-service
      context: .
      docker:
        dockerfile: microservices/services/llm-service/Dockerfile
      sync:
        manual:
          - src: "microservices/services/llm-service/src/**/*.py"
            dest: "/app/microservices/services/llm-service/src"
          - src: "microservices/shared/**/*.py"
            dest: "/app/microservices/shared"
    - image: career-advisor/messages-service
      context: .
      docker:
        dockerfile: microservices/services/messages-service/Dockerfile
      sync:
        manual:
          - src: "microservices/services/messages-service/src/**/*.py"
            dest: "/app/microservices/services/messages-service/src"
          - src: "microservices/shared/**/*.py"
            dest: "/app/microservices/shared"
    - image: career-advisor/prompts-service
      context: .
      docker:
        dockerfile: microservices/services/prompts-service/Dockerfile
      sync:
        manual:
          - src: "microservices/services/prompts-service/src/**/*.py"
            dest: "/app/microservices/services/prompts-service/src"
          - src: "microservices/shared/**/*.py"
            dest: "/app/microservices/shared"
    - image: career-advisor/users-service
      context: .
      docker:
        dockerfile: microservices/services/users-service/Dockerfile
      sync:
        manual:
          - src: "microservices/services/users-service/src/**/*.py"
            dest: "/app/microservices/services/users-service/src"
          - src: "microservices/shared/**/*.py"
            dest: "/app/microservices/shared"
manifests:
  rawYaml:
    - k8s/namespace.yaml
    - k8s/configmap.yaml
    - k8s/postgres.yaml
    - k8s/users-service.yaml
    - k8s/conversations-service.yaml
    - k8s/messages-service.yaml
    - k8s/prompts-service.yaml
    - k8s/llm-service.yaml
    - k8s/ingress.yaml

# Port forwarding for development
portForward:
  - resourceType: service
    resourceName: users-service
    namespace: career-advisor
    port: 8000
    localPort: 8001
  - resourceType: service
    resourceName: conversations-service
    namespace: career-advisor
    port: 8000
    localPort: 8002
  - resourceType: service
    resourceName: messages-service
    namespace: career-advisor
    port: 8000
    localPort: 8003
  - resourceType: service
    resourceName: prompts-service
    namespace: career-advisor
    port: 8000
    localPort: 8004
  - resourceType: service
    resourceName: llm-service
    namespace: career-advisor
    port: 8000
    localPort: 8005
  - resourceType: service
    resourceName: postgres-service
    namespace: career-advisor
    port: 5432
    localPort: 5432

# Development profiles
profiles:
  - name: dev
    build:
      local:
        push: false
    portForward:
      - resourceType: service
        resourceName: users-service
        namespace: career-advisor
        port: 8000
        localPort: 8001
      - resourceType: service
        resourceName: conversations-service
        namespace: career-advisor
        port: 8000
        localPort: 8002
      - resourceType: service
        resourceName: messages-service
        namespace: career-advisor
        port: 8000
        localPort: 8003
      - resourceType: service
        resourceName: prompts-service
        namespace: career-advisor
        port: 8000
        localPort: 8004
      - resourceType: service
        resourceName: llm-service
        namespace: career-advisor
        port: 8000
        localPort: 8005
      - resourceType: service
        resourceName: postgres-service
        namespace: career-advisor
        port: 5432
        localPort: 5432
