apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversations-service
  namespace: career-advisor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversations-service
  template:
    metadata:
      labels:
        app: conversations-service
    spec:
      containers:
      - name: conversations-service
        image: career-advisor/conversations-service:latest
        imagePullPolicy: Never  # For local development
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: career-advisor-config
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: career-advisor-config
              key: DATABASE_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: conversations-service
  namespace: career-advisor
spec:
  selector:
    app: conversations-service
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
