apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: prompts-service-hpa
  namespace: career-advisor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prompts-service
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
