"""create default user

Revision ID: 1eda9181f560
Revises: 48bed35589a7
Create Date: 2025-08-24 19:24:43.773833

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid

# revision identifiers, used by Alembic.
revision: str = "1eda9181f560"
down_revision: Union[str, None] = "48bed35589a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_table = sa.Table("users", sa.MetaData(), autoload_with=op.get_bind())

    op.bulk_insert(
        user_table,
        [{"id": uuid.uuid4(), "name": "Jesus", "email": "hola@jesusrugama.com"}],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE users")
    # ### end Alembic commands ###
