version: '3.8'

services:
  # PostgreSQL database for development
  postgres:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_DB: career_advisor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Prompts Service (Development Mode with Volume Mounts)
  prompts-service:
    build:
      context: ../
      dockerfile: microservices/services/prompts-service/Dockerfile
    ports:
      - "8004:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/career_advisor
      - PYTHONDONTWRITEBYTECODE=1  # Don't write .pyc files
      - PYTHONUNBUFFERED=1         # Force stdout/stderr to be unbuffered
    volumes:
      # Mount source code for real-time editing
      - ./services/prompts-service/src:/app/microservices/services/prompts-service/src
      - ./shared:/app/microservices/shared
    depends_on:
      postgres:
        condition: service_healthy
    # Keep container alive for debugging
    tty: true
    stdin_open: true
    # Auto-restart on file changes with uvicorn --reload
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  postgres_dev_data:
