name: Microservices Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-microservices:
    runs-on: ubuntu-latest
    continue-on-error: true
    
    strategy:
      matrix:
        service: [prompts-service, conversations-service, users-service]
    
    services:
      postgres:
        image: pgvector/pgvector:pg15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: career_advisor_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Test microservice
      uses: ./.github/actions/test-service
      with:
        service-name: ${{ matrix.service }}
        python-version: '3.10'
        test-database-url: postgresql+asyncpg://postgres:postgres@localhost:5432/career_advisor_test
